# Generated by Django 5.0.6 on 2024-11-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_driver_location_sharing_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
