# Generated by Django 5.0.6 on 2024-11-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0003_remove_driverlocation_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='location_sharing_active',
        ),
        migrations.RemoveField(
            model_name='driverlocation',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking_app.driver'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='location_sharing_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
